/**
 * AI 公益中转站导航 - 默认数据配置
 * 支持直接本地运行，也支持服务器环境通过 fetch('data/sites.json') 覆盖
 */
window.DEFAULT_CONFIG = {
  siteName: "AI 公益中转导航",
  siteSlogan: "精选高额度公益 AI 中转站 · 一键直达领取免费额度",
  heroTitle: "⚡ 免费领 AI 额度 · 旗舰中转站精选导航",
  heroSub: "全网精选优质高额度公益中转站，全面支持 gpt-5.6-sol / claude-opus-5 / DeepSeek-R1 全系列旗舰大模型。点击注册即送丰厚额度，使用专属邀请码更有额外加赠！",
  noticeTitle: "📢 站长福利提示 & 旗舰模型上线",
  noticeContent: "1. 全站收录中转站已全面接入 gpt-5.6-sol、claude-opus-5 等超旗舰模型！\n2. 强烈建议通过本站专属链接注册，可额外激活 $20~$25 专属邀请加赠礼包！\n3. 每日坚持签到，可无限白嫖日常使用额度。\n4. 推荐将 5 个站点全部注册并配置到 Cherry Studio、NextChat、Cursor 轮换使用，额度永不枯竭！",
  noticeVersion: 3,
  contactUrl: "https://t.me/",
  updatedAt: "2026-08-20"
};

window.DEFAULT_SITES = [
  {
    id: "gorouter",
    name: "GoRouter",
    domain: "gorouter.app",
    link: "https://gorouter.app/sign-up?aff=ekWb",
    affCode: "ekWb",
    registerBonus: "$70 (1:1真实无套路)",
    inviteBonus: "+$20 专属加赠",
    dailyBonus: "每日赠送额度",
    bonusValue: 150,
    dailyValue: 15,
    tags: ["1:1真实扣费", "gpt-5.6-sol", "claude-opus-5", "编程开发王", "不限并发"],
    models: ["gpt-5.6-sol", "claude-opus-5", "deepseek-r1"],
    desc: "独家 1:1 真实扣费无虚标，不锁并发，实测耐用度碾压高虚标站点！全面支持 gpt-5.6-sol / claude-opus-5 旗舰模型。",
    recommend: "⚠️ 站长实测爆料：别看标价 $70，实测扣费无倍率虚标！实际可用请求次数比其他标 $120 的站多 2 倍，Cursor / VS Code 编程神器！",
    status: "active",
    badge: "🔥 真实耐用王 · 1:1无虚标",
    pinned: true,
    urgent: true,
    icon: "⚡",
    color: "linear-gradient(135deg, #f59e0b, #ef4444)",
    date: "2026-08-20"
  },
  {
    id: "agentrouter",
    name: "AgentRouter",
    domain: "agentrouter.org",
    link: "https://agentrouter.org/register?aff=WTR4",
    affCode: "WTR4",
    registerBonus: "$100",
    inviteBonus: "+$25 专属加赠",
    dailyBonus: "$25 / 每日签到",
    bonusValue: 125,
    dailyValue: 25,
    tags: ["每日签到", "高额奖励", "claude-opus-5", "全模型旗舰"],
    models: ["claude-opus-5", "gpt-5.6-sol", "deepseek-r1"],
    desc: "聚合全球顶尖算力中转节点，全网首发支持 claude-opus-5 / gpt-5.6-sol，注册即领高额体验额度，配合邀请码额外加赠！",
    recommend: "首日合计立领 $125，每日签到再领 $25，额度极其抗用，站长主推！",
    status: "active",
    badge: "👑 综合旗舰之王",
    pinned: true,
    urgent: false,
    icon: "⚡",
    color: "linear-gradient(135deg, #6366f1, #8b5cf6)",
    date: "2026-08-20"
  },
  {
    id: "seekai",
    name: "SeekAi",
    domain: "seekai.cc",
    link: "https://seekai.cc/sign-up?aff=1PrI",
    affCode: "1PrI",
    registerBonus: "$120",
    inviteBonus: "+$20 邀请奖励",
    dailyBonus: "$20 / 每日签到",
    bonusValue: 140,
    dailyValue: 20,
    tags: ["每日签到", "超大额度", "gpt-5.6-sol", "深度思考R1"],
    models: ["deepseek-r1", "gpt-5.6-sol", "claude-opus-5"],
    desc: "全面优化 DeepSeek-R1 与 gpt-5.6-sol 旗舰大模型，注册即送 $120，每日签到稳定到账 $20。",
    recommend: "豪华新手礼包，每日签到稳定到账 $20，深度思考推理模型响应超快！",
    status: "active",
    badge: "💎 每日高额续期",
    pinned: false,
    urgent: true,
    icon: "🧠",
    color: "linear-gradient(135deg, #10b981, #059669)",
    date: "2026-08-20"
  },
  {
    id: "tabitoken",
    name: "TaBiToken",
    domain: "tabitoken.com",
    link: "https://tabitoken.com/sign-up?aff=DgIc",
    affCode: "DgIc",
    registerBonus: "$120",
    inviteBonus: "+$20 邀请奖励",
    dailyBonus: "每日赠送额度",
    bonusValue: 140,
    dailyValue: 10,
    tags: ["每日签到", "超大额度", "多模态生图", "claude-opus-5"],
    models: ["gpt-5.6-sol", "claude-opus-5", "midjourney/flux"],
    desc: "超高免费额度中转平台，深度支持各类视觉生图、多模态解析与万级高并发调用。",
    recommend: "注册登录直送 $120，生图与长文本体验极佳，多模型并发支持！",
    status: "active",
    badge: "🎁 超大多模态额度",
    pinned: false,
    urgent: false,
    icon: "🔮",
    color: "linear-gradient(135deg, #ec4899, #f43f5e)",
    date: "2026-08-20"
  },
  {
    id: "kktoken",
    name: "KKtoken AI",
    domain: "kktoken.cc",
    link: "https://kktoken.cc/sign-up?aff=F4qL",
    affCode: "F4qL",
    registerBonus: "$100",
    inviteBonus: "+$20 专属加赠",
    dailyBonus: "约 $22 / 每日签到",
    bonusValue: 120,
    dailyValue: 22,
    tags: ["每日签到", "GitHub登录", "gpt-5.6-sol", "claude-opus-5", "纯净防刷"],
    models: ["gpt-5.6-sol", "claude-opus-5", "deepseek-r1"],
    desc: "支持 GitHub 授权一键登录，纯净防刷高可用中转。全面支持 gpt-5.6-sol / claude-opus-5 旗舰模型，每日签到领约 $22 稳定续期。",
    recommend: "GitHub 快捷登录免手机邮箱验证，每日签到稳定领 $22，节点纯净响应极快，主力备用必备！",
    status: "active",
    badge: "🛡️ 纯净高速",
    pinned: false,
    urgent: false,
    icon: "🛡️",
    color: "linear-gradient(135deg, #0ea5e9, #6366f1)",
    date: "2026-09-04"
  }
];
