/**
 * AI 公益中转站导航 - 默认数据配置
 * 支持直接本地运行，也支持服务器环境通过 fetch('data/sites.json') 覆盖
 */
window.DEFAULT_CONFIG = {
  siteName: "AI 公益中转导航",
  siteSlogan: "精选高额度公益 AI 中转站 · 一键直达领取免费额度",
  heroTitle: "免费领取 AI 额度 · 公益中转站精选导航",
  heroSub: "收录全网优质高额度公益中转站，支持 Claude 3.7 / GPT-4o / DeepSeek-R1 全模型。注册即领高额免费额度，专属邀请码额外加赠！",
  noticeTitle: "📢 站长福利提示 & 使用必读",
  noticeContent: "1. 强烈建议通过本站专属链接注册，可额外激活 $20~$25 专属邀请加赠礼包！\n2. 每日坚持签到，可无限白嫖日常使用额度。\n3. 所有中转站均支持接入 Cherry Studio、NextChat、Chatbox、Cursor 等常用客户端。\n4. 本站仅做信息聚合与邀请码推荐，请妥善保管个人 API Key 与隐私数据。",
  noticeVersion: 1,
  contactUrl: "https://t.me/",
  updatedAt: "2026-08-20"
};

window.DEFAULT_SITES = [
  {
    id: "agentrouter",
    name: "AgentRouter",
    domain: "agentrouter.org",
    link: "https://agentrouter.org/register?aff=WTR4",
    affCode: "WTR4",
    registerBonus: "$100",
    inviteBonus: "+$25 专属加赠",
    dailyBonus: "$25 / 每日签到",
    bonusValue: 125,
    dailyValue: 25,
    tags: ["每日签到", "高额奖励", "编程神器", "全模型支持"],
    desc: "聚合全球顶尖大模型中转节点，注册即领高额体验额度，配合专属邀请码立享额外加赠！",
    recommend: "首日合计立领 $125，每日签到再领 $25，额度极其抗用，站长主推！",
    status: "active",
    badge: "🔥 站长力荐",
    pinned: true,
    urgent: true,
    icon: "⚡",
    color: "linear-gradient(135deg, #6366f1, #8b5cf6)",
    date: "2026-08-20"
  },
  {
    id: "tabitoken",
    name: "TaBiToken",
    domain: "tabitoken.com",
    link: "https://tabitoken.com/sign-up?aff=DgIc",
    affCode: "DgIc",
    registerBonus: "$120",
    inviteBonus: "+$20 邀请奖励",
    dailyBonus: "每日赠送额度",
    bonusValue: 140,
    dailyValue: 10,
    tags: ["每日签到", "超大额度", "多模态生图", "极速稳定"],
    desc: "超高免费额度中转平台，深度支持各类视觉生图、多模态解析与高并发日常对话。",
    recommend: "注册登录直送 $120，生图与长文本体验极佳，多模型并发支持！",
    status: "active",
    badge: "🎁 超大额度",
    pinned: true,
    urgent: false,
    icon: "🔮",
    color: "linear-gradient(135deg, #ec4899, #f43f5e)",
    date: "2026-08-20"
  },
  {
    id: "seekai",
    name: "SeekAi",
    domain: "seekai.cc",
    link: "https://seekai.cc/sign-up?aff=1PrI",
    affCode: "1PrI",
    registerBonus: "$120",
    inviteBonus: "+$20 邀请奖励",
    dailyBonus: "$20 / 每日签到",
    bonusValue: 140,
    dailyValue: 20,
    tags: ["每日签到", "超大额度", "深度思考R1", "热门优选"],
    desc: "全面优化 DeepSeek-R1/V3 与主流顶级大模型，注册即送 $120，每日签到稳定续期。",
    recommend: "豪华新手礼包，每日签到稳定到账 $20，深度思考推理模型响应超快！",
    status: "active",
    badge: "💎 每日高额续期",
    pinned: false,
    urgent: true,
    icon: "🧠",
    color: "linear-gradient(135deg, #10b981, #059669)",
    date: "2026-08-20"
  },
  {
    id: "gorouter",
    name: "GoRouter",
    domain: "gorouter.app",
    link: "https://gorouter.app/sign-up?aff=ekWb",
    affCode: "ekWb",
    registerBonus: "$70",
    inviteBonus: "+$20 邀请奖励",
    dailyBonus: "每日赠送额度",
    bonusValue: 90,
    dailyValue: 10,
    tags: ["每日签到", "低延迟", "极速响应", "高稳定性"],
    desc: "专为开发者与编程辅助打造的极速低延迟节点，API 响应毫秒级，开发首选。",
    recommend: "低延迟极速响应，极适合接入 Cursor / VS Code / Claude Code 等编程开发工具。",
    status: "active",
    badge: "⚡ 极速低延迟",
    pinned: false,
    urgent: false,
    icon: "🚀",
    color: "linear-gradient(135deg, #06b6d4, #3b82f6)",
    date: "2026-08-20"
  }
];
